/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.serviciopasantias.Vista.Menu_Profesor;

import proyecto.serviciopasantias.Vista.Menu_Estudiante.*;
import proyecto.serviciopasantias.Vista.Login;

/**
 *
 * @author Windows
 */
public class InformacionPasantiaProfesor extends javax.swing.JPanel {

    /**
     * Creates new form InformacionPersonal
     */
    public InformacionPasantiaProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Boton_Editar = new javax.swing.JLabel();
        Img_atras = new javax.swing.JLabel();
        NombreEntry = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NombreEntry1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NombreEntry2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NombreEntry3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        NombreEntry4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        NombreEntry5 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1150, 420));

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(148, 180, 59));
        jPanel2.setLayout(null);

        Boton_Editar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Boton_Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_Editar.setText("Calificar");
        jPanel2.add(Boton_Editar);
        Boton_Editar.setBounds(0, 0, 140, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(990, 330, 140, 60);

        Img_atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/Atras.png"))); // NOI18N
        Img_atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Img_atrasMouseClicked(evt);
            }
        });
        jPanel1.add(Img_atras);
        Img_atras.setBounds(10, 10, 33, 33);

        NombreEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry.setEnabled(false);
        NombreEntry.setFocusCycleRoot(true);
        NombreEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntryActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry);
        NombreEntry.setBounds(150, 230, 770, 90);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Calificación:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(550, 150, 100, 25);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Estudiante:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 50, 90, 25);

        NombreEntry1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry1.setEnabled(false);
        NombreEntry1.setFocusCycleRoot(true);
        NombreEntry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntry1ActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry1);
        NombreEntry1.setBounds(660, 150, 70, 25);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Empresa:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 100, 90, 25);

        NombreEntry2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry2.setEnabled(false);
        NombreEntry2.setFocusCycleRoot(true);
        NombreEntry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntry2ActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry2);
        NombreEntry2.setBounds(150, 100, 250, 25);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("Pasantia:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 150, 90, 25);

        NombreEntry3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry3.setEnabled(false);
        NombreEntry3.setFocusCycleRoot(true);
        NombreEntry3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntry3ActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry3);
        NombreEntry3.setBounds(150, 150, 250, 25);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setText("Descrición:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 230, 90, 25);

        NombreEntry4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry4.setEnabled(false);
        NombreEntry4.setFocusCycleRoot(true);
        NombreEntry4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntry4ActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry4);
        NombreEntry4.setBounds(150, 50, 250, 25);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("Introducción:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(550, 50, 100, 25);

        NombreEntry5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry5.setEnabled(false);
        NombreEntry5.setFocusCycleRoot(true);
        NombreEntry5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntry5ActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry5);
        NombreEntry5.setBounds(660, 50, 250, 80);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(500, 0, 3, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Img_atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Img_atrasMouseClicked
        Login b = new Login();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Img_atrasMouseClicked

    private void NombreEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntryActionPerformed

    private void NombreEntry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntry1ActionPerformed

    private void NombreEntry2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntry2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntry2ActionPerformed

    private void NombreEntry3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntry3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntry3ActionPerformed

    private void NombreEntry4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntry4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntry4ActionPerformed

    private void NombreEntry5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntry5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntry5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boton_Editar;
    private javax.swing.JLabel Img_atras;
    private javax.swing.JTextField NombreEntry;
    private javax.swing.JTextField NombreEntry1;
    private javax.swing.JTextField NombreEntry2;
    private javax.swing.JTextField NombreEntry3;
    private javax.swing.JTextField NombreEntry4;
    private javax.swing.JTextField NombreEntry5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
