/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.serviciopasantias.Vista.Menu_Profesor;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import proyecto.serviciopasantias.Modelo.Docentes;
import proyecto.serviciopasantias.Modelo.LoginForAll;


/**
 *
 * @author Windows
 */
public class InformacionPersonalProfesor extends javax.swing.JPanel {

    /**
     * Creates new form InformacionPersonal
     */
    public InformacionPersonalProfesor() {
        initComponents();
        
        Contraseña2.hide();
        NombreEntry.setText(Docentes.nombre);
        ApellidoEntry.setText(Docentes.apellido);
        IDEntry.setText(Docentes.tipo_id);
        IDEntry1.setText(Docentes.no_id);
        LugarEntry.setText(Docentes.lugar);
        TelefonoEntry.setText(Docentes.telefono);
        TelefonoEntry1.setText(Docentes.extension);
        CorreoEntry.setText(Docentes.correo);
        DepartamentoEntry.setText(Docentes.departamento);
        ContraseñaEntry.setText(LoginForAll.passwordu);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CorreoEntry = new javax.swing.JTextField();
        ApellidoEntry = new javax.swing.JTextField();
        IDEntry = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TelefonoEntry = new javax.swing.JTextField();
        Boton_Editar = new javax.swing.JPanel();
        LabelEditar = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NombreEntry = new javax.swing.JTextField();
        LugarEntry = new javax.swing.JTextField();
        DepartamentoEntry = new javax.swing.JTextField();
        Boton_Guardar = new javax.swing.JPanel();
        LabelGuardar = new javax.swing.JLabel();
        IDEntry1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        Contraseña1 = new javax.swing.JLabel();
        Contraseña2 = new javax.swing.JLabel();
        ContraseñaEntry = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        TelefonoEntry1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1150, 420));

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("No. ID:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(325, 120, 70, 25);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Nombres:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 20, 160, 25);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Apellidos:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 70, 80, 25);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Tipo ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 120, 60, 25);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Departamento:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(610, 170, 110, 25);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Correo Institucional:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(610, 20, 150, 25);

        CorreoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CorreoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CorreoEntry.setEnabled(false);
        CorreoEntry.setNextFocusableComponent(TelefonoEntry);
        jPanel1.add(CorreoEntry);
        CorreoEntry.setBounds(760, 20, 350, 25);

        ApellidoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ApellidoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ApellidoEntry.setEnabled(false);
        ApellidoEntry.setNextFocusableComponent(IDEntry);
        jPanel1.add(ApellidoEntry);
        ApellidoEntry.setBounds(130, 70, 400, 25);

        IDEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry.setEnabled(false);
        IDEntry.setNextFocusableComponent(IDEntry1);
        IDEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntryActionPerformed(evt);
            }
        });
        jPanel1.add(IDEntry);
        IDEntry.setBounds(130, 120, 190, 25);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setText("Teléfono:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(610, 70, 70, 25);

        TelefonoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TelefonoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TelefonoEntry.setEnabled(false);
        TelefonoEntry.setNextFocusableComponent(TelefonoEntry1);
        TelefonoEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoEntryActionPerformed(evt);
            }
        });
        jPanel1.add(TelefonoEntry);
        TelefonoEntry.setBounds(710, 70, 400, 25);

        Boton_Editar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Editar.setLayout(null);

        LabelEditar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEditar.setText("Editar");
        LabelEditar.setNextFocusableComponent(NombreEntry);
        LabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEditarMouseClicked(evt);
            }
        });
        LabelEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelEditarKeyPressed(evt);
            }
        });
        Boton_Editar.add(LabelEditar);
        LabelEditar.setBounds(0, 0, 280, 60);

        jPanel1.add(Boton_Editar);
        Boton_Editar.setBounds(595, 340, 280, 60);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("Lugar de Expedición:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 170, 170, 25);

        NombreEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry.setEnabled(false);
        NombreEntry.setFocusCycleRoot(true);
        NombreEntry.setNextFocusableComponent(ApellidoEntry);
        NombreEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntryActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry);
        NombreEntry.setBounds(130, 20, 400, 25);

        LugarEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LugarEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LugarEntry.setEnabled(false);
        LugarEntry.setNextFocusableComponent(ContraseñaEntry);
        LugarEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarEntryActionPerformed(evt);
            }
        });
        jPanel1.add(LugarEntry);
        LugarEntry.setBounds(190, 170, 340, 25);

        DepartamentoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        DepartamentoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DepartamentoEntry.setEnabled(false);
        DepartamentoEntry.setFocusCycleRoot(true);
        DepartamentoEntry.setNextFocusableComponent(LabelGuardar);
        DepartamentoEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoEntryActionPerformed(evt);
            }
        });
        jPanel1.add(DepartamentoEntry);
        DepartamentoEntry.setBounds(730, 170, 380, 25);

        Boton_Guardar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Guardar.setLayout(null);

        LabelGuardar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGuardar.setText("Guardar");
        LabelGuardar.setEnabled(false);
        LabelGuardar.setNextFocusableComponent(LabelEditar);
        LabelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelGuardarMouseClicked(evt);
            }
        });
        LabelGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelGuardarKeyPressed(evt);
            }
        });
        Boton_Guardar.add(LabelGuardar);
        LabelGuardar.setBounds(0, 0, 280, 60);

        jPanel1.add(Boton_Guardar);
        Boton_Guardar.setBounds(275, 340, 280, 60);

        IDEntry1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDEntry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry1.setEnabled(false);
        IDEntry1.setNextFocusableComponent(LugarEntry);
        IDEntry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntry1ActionPerformed(evt);
            }
        });
        jPanel1.add(IDEntry1);
        IDEntry1.setBounds(380, 120, 150, 25);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(573, 0, 2, 300);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("Contraseña:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 220, 150, 25);

        Contraseña1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/PasswordUn1.png"))); // NOI18N
        Contraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Contraseña1MouseClicked(evt);
            }
        });
        jPanel1.add(Contraseña1);
        Contraseña1.setBounds(500, 223, 20, 20);

        Contraseña2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/eye1.png"))); // NOI18N
        Contraseña2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Contraseña2MouseClicked(evt);
            }
        });
        jPanel1.add(Contraseña2);
        Contraseña2.setBounds(500, 223, 20, 20);

        ContraseñaEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ContraseñaEntry.setText("jPasswordField1");
        ContraseñaEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContraseñaEntry.setEnabled(false);
        ContraseñaEntry.setNextFocusableComponent(CorreoEntry);
        jPanel1.add(ContraseñaEntry);
        ContraseñaEntry.setBounds(130, 220, 400, 25);

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel24.setText("Extensión:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(610, 120, 70, 25);

        TelefonoEntry1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TelefonoEntry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TelefonoEntry1.setEnabled(false);
        TelefonoEntry1.setNextFocusableComponent(DepartamentoEntry);
        TelefonoEntry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoEntry1ActionPerformed(evt);
            }
        });
        jPanel1.add(TelefonoEntry1);
        TelefonoEntry1.setBounds(710, 120, 400, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IDEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntryActionPerformed

    private void TelefonoEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoEntryActionPerformed

    private void LabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEditarMouseClicked
        String pass = JOptionPane.showInputDialog("Ingrese su contraseña para hacer cambios");
        if (pass.equals(LoginForAll.passwordu)){
            LabelEditar.setEnabled(false);
            LabelGuardar.setEnabled(true);
            ContraseñaEntry.setEnabled(true);
            TelefonoEntry.setEnabled(true);
            TelefonoEntry1.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LabelEditarMouseClicked

    private void LabelEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelEditarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String pass = JOptionPane.showInputDialog("Ingrese su contraseña para hacer cambios");
            if (pass.equals(LoginForAll.passwordu)){
                LabelEditar.setEnabled(false);
                LabelGuardar.setEnabled(true);
                ContraseñaEntry.setEnabled(true);
                TelefonoEntry.setEnabled(true);
                TelefonoEntry1.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_LabelEditarKeyPressed

    private void NombreEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntryActionPerformed

    private void LugarEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarEntryActionPerformed

    private void DepartamentoEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartamentoEntryActionPerformed

    private void LabelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelGuardarMouseClicked
        String resultado = Docentes.CambiarDatos(ContraseñaEntry.getText(), LoginForAll.usuario, TelefonoEntry.getText(), TelefonoEntry1.getText());
        if (resultado.equals("Datos Actualizados")){
            JOptionPane.showMessageDialog(this, "Los datos han sido actualizados con éxito", "Cambio Exitoso", JOptionPane.INFORMATION_MESSAGE);
            LabelEditar.setEnabled(true);
            LabelGuardar.setEnabled(false);
            ContraseñaEntry.setEnabled(false);
            TelefonoEntry.setEnabled(false);
            TelefonoEntry1.setEnabled(false);
        }
        else if (resultado.equals("Error")){
            JOptionPane.showMessageDialog(this, "Ha habido un error en el cambio de credenciales", "Error", JOptionPane.ERROR_MESSAGE);   
        }
        else{             
            JOptionPane.showMessageDialog(this, resultado , "Ingreso Fallido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LabelGuardarMouseClicked

    private void LabelGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelGuardarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String resultado = Docentes.CambiarDatos(ContraseñaEntry.getText(), LoginForAll.usuario, TelefonoEntry.getText(), TelefonoEntry1.getText());
            if (resultado.equals("Datos Actualizados")){
                JOptionPane.showMessageDialog(this, "Los datos han sido actualizados con éxito", "Cambio Exitoso", JOptionPane.INFORMATION_MESSAGE);
                LabelEditar.setEnabled(true);
                LabelGuardar.setEnabled(false);
                ContraseñaEntry.setEnabled(false);
                TelefonoEntry.setEnabled(false);
                TelefonoEntry1.setEnabled(false);
            }
            else if (resultado.equals("Error")){
                JOptionPane.showMessageDialog(this, "Ha habido un error en el cambio de credenciales", "Error", JOptionPane.ERROR_MESSAGE);   
            }
            else{             
                JOptionPane.showMessageDialog(this, resultado , "Ingreso Fallido", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_LabelGuardarKeyPressed

    private void IDEntry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntry1ActionPerformed

    private void Contraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contraseña1MouseClicked
        if (ContraseñaEntry.isEnabled() == true){
            ContraseñaEntry.setEchoChar((char)0);
            Contraseña2.show();
            Contraseña2.setEnabled(true);
            Contraseña1.hide();
            Contraseña1.setEnabled(false);
        }
    }//GEN-LAST:event_Contraseña1MouseClicked

    private void Contraseña2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contraseña2MouseClicked
        if (ContraseñaEntry.isEnabled() == true){
            ContraseñaEntry.setEchoChar('*');
            Contraseña1.show();
            Contraseña1.setEnabled(true);
            Contraseña2.hide();
            Contraseña2.setEnabled(false);
        }
    }//GEN-LAST:event_Contraseña2MouseClicked

    private void TelefonoEntry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoEntry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoEntry1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoEntry;
    private javax.swing.JPanel Boton_Editar;
    private javax.swing.JPanel Boton_Guardar;
    private javax.swing.JLabel Contraseña1;
    private javax.swing.JLabel Contraseña2;
    private javax.swing.JPasswordField ContraseñaEntry;
    private javax.swing.JTextField CorreoEntry;
    private javax.swing.JTextField DepartamentoEntry;
    private javax.swing.JTextField IDEntry;
    private javax.swing.JTextField IDEntry1;
    private javax.swing.JLabel LabelEditar;
    private javax.swing.JLabel LabelGuardar;
    private javax.swing.JTextField LugarEntry;
    private javax.swing.JTextField NombreEntry;
    private javax.swing.JTextField TelefonoEntry;
    private javax.swing.JTextField TelefonoEntry1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
