/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.serviciopasantias.Vista;

import java.sql.DriverManager;
import java.sql.SQLException;
import com.mysql.jdbc.Connection;
import java.awt.Color;



/**
 *
 * @author Windows
 */
public class Loginn extends javax.swing.JFrame {
    
    
    
    
    
    /*
    Iniciando conexión con la base de datos
    */
    
    private static Connection con;
    
    public static final String driver="com.mysql.jdbc.Driver";
    public static final String Url = "jdbc:mysql://localhost:3306/scripttestnicos";
    public static final String User = "root";
    public static final String Password = "";
    
    
    public void conexion(){
        con=null;
        try{
            Class.forName(driver);
            
            con= (Connection) DriverManager.getConnection(Url, User, Password);
            
            if (con!=null){
                System.out.println("Soy GEi");
            }
            
        }
        
        
        catch (ClassNotFoundException | SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * Creates new form Loginn
     */
    public Loginn() {
        initComponents();
        
        
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Ingresar_Usuario = new javax.swing.JTextField();
        Boton_Iniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Ingresar_Pass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(148, 180, 59));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(148, 180, 59));
        jPanel1.setForeground(new java.awt.Color(148, 180, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(86, 90, 92));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿No está registrado? Cree su cuenta.");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 910, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/User.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 980, 0));

        Ingresar_Usuario.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        Ingresar_Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Ingresar_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ingresar_Usuario.setText("Ingrese Usuario");
        Ingresar_Usuario.setToolTipText("Usuario");
        Ingresar_Usuario.setBorder(null);
        Ingresar_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Ingresar_Usuario.setName(""); // NOI18N
        Ingresar_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ingresar_UsuarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Ingresar_UsuarioMouseReleased(evt);
            }
        });
        Ingresar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_UsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(Ingresar_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 193, 300, 50));
        Ingresar_Usuario.getAccessibleContext().setAccessibleName("");

        Boton_Iniciar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Iniciar.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Boton_Iniciar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Iniciar.setText("Iniciar Sesión");
        Boton_Iniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_IniciarActionPerformed(evt);
            }
        });
        jPanel3.add(Boton_Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 171, 39));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingrese su usuario y contraseña");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 53));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/PasswordUn.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 250, 50));

        Ingresar_Pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ingresar_Pass.setText("************");
        Ingresar_Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ingresar_PassMousePressed(evt);
            }
        });
        jPanel3.add(Ingresar_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 300, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 970, 450));

        jPanel2.setBackground(new java.awt.Color(86, 90, 92));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/LogoUN.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 110));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Servicio de pasantias");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 560, 53));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/Atras.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/Adelante.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1660, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1660, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_IniciarActionPerformed
        conexion();
    }//GEN-LAST:event_Boton_IniciarActionPerformed

    private void Ingresar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_UsuarioActionPerformed

    private void Ingresar_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioMousePressed
        if (Ingresar_Usuario.getText().equals("Ingrese Usuario")){
            
            Ingresar_Usuario.setText("");
            Ingresar_Usuario.setForeground(Color.black);
  
        }
        
        if (String.valueOf(Ingresar_Pass.getPassword()).isEmpty()){
            
            Ingresar_Pass.setText("************");
            Ingresar_Pass.setForeground(Color.gray);   
        }
        
         
    }//GEN-LAST:event_Ingresar_UsuarioMousePressed

    private void Ingresar_UsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioMouseReleased
        
    }//GEN-LAST:event_Ingresar_UsuarioMouseReleased

    private void Ingresar_PassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_PassMousePressed

                
        if (Ingresar_Usuario.getText().isEmpty()){
            
            Ingresar_Usuario.setText("Ingrese Usuario");
            Ingresar_Usuario.setForeground(Color.gray);
  
        }
        
        if (String.valueOf(Ingresar_Pass.getPassword()).equals("************")){
            
            Ingresar_Pass.setText("");
            Ingresar_Pass.setForeground(Color.black);   
        }
    }//GEN-LAST:event_Ingresar_PassMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Iniciar;
    private javax.swing.JPasswordField Ingresar_Pass;
    private javax.swing.JTextField Ingresar_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
