/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.serviciopasantias.Vista;

import java.awt.Color;



/**
 *
 * @author Windows
 */
public class Login extends javax.swing.JFrame {
    
    
    
    
    
    /*
    Iniciando conexión con la base de datos
    */
    /**
     * Creates new form Loginn
     */
    public Login() {
        initComponents();
        
        
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Ingresar_Usuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Ingresar_Pass = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Ass = new javax.swing.JPanel();
        Boton_Ingresar = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        as = new javax.swing.JPanel();
        Boton_Registrar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(148, 180, 59));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(148, 180, 59));
        jPanel1.setForeground(new java.awt.Color(148, 180, 59));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(86, 90, 92));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/User.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(580, 250, 35, 35);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 56, 980, 0);

        Ingresar_Usuario.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        Ingresar_Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Ingresar_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ingresar_Usuario.setText("Ingrese Usuario");
        Ingresar_Usuario.setToolTipText("Usuario");
        Ingresar_Usuario.setBorder(null);
        Ingresar_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ingresar_Usuario.setName(""); // NOI18N
        Ingresar_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ingresar_UsuarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Ingresar_UsuarioMouseReleased(evt);
            }
        });
        Ingresar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_UsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(Ingresar_Usuario);
        Ingresar_Usuario.setBounds(570, 240, 300, 50);
        Ingresar_Usuario.getAccessibleContext().setAccessibleName("");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/PasswordUn.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(580, 330, 36, 34);

        Ingresar_Pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ingresar_Pass.setText("************");
        Ingresar_Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ingresar_PassMousePressed(evt);
            }
        });
        Ingresar_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_PassActionPerformed(evt);
            }
        });
        jPanel3.add(Ingresar_Pass);
        Ingresar_Pass.setBounds(570, 320, 300, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/Capybara.png"))); // NOI18N
        jPanel4.add(jLabel10);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(630, 20, 170, 140);

        Ass.setBackground(new java.awt.Color(148, 180, 59));
        Ass.setLayout(null);

        Boton_Ingresar.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        Boton_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_Ingresar.setText("Ingresar");
        Boton_Ingresar.setToolTipText("");
        Ass.add(Boton_Ingresar);
        Boton_Ingresar.setBounds(0, 0, 230, 50);

        jPanel3.add(Ass);
        Ass.setBounds(600, 410, 230, 50);

        jPanel7.setLayout(null);
        jPanel3.add(jPanel7);
        jPanel7.setBounds(590, 400, 250, 70);

        jPanel9.setBackground(new java.awt.Color(148, 180, 59));
        jPanel3.add(jPanel9);
        jPanel9.setBounds(600, 410, 230, 50);

        jPanel10.setBackground(new java.awt.Color(148, 180, 59));
        jPanel3.add(jPanel10);
        jPanel10.setBounds(600, 410, 230, 50);

        jPanel11.setBackground(new java.awt.Color(148, 180, 59));
        jPanel3.add(jPanel11);
        jPanel11.setBounds(600, 410, 230, 50);

        jPanel6.setLayout(null);

        as.setBackground(new java.awt.Color(148, 180, 59));
        as.setToolTipText("");
        as.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asMouseClicked(evt);
            }
        });
        as.setLayout(null);

        Boton_Registrar.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        Boton_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_Registrar.setText("Registrarse");
        Boton_Registrar.setToolTipText("");
        Boton_Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Boton_Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_RegistrarMouseClicked(evt);
            }
        });
        as.add(Boton_Registrar);
        Boton_Registrar.setBounds(0, 0, 230, 50);

        jPanel6.add(as);
        as.setBounds(10, 10, 230, 50);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(590, 490, 250, 70);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema de Practicas y Pasantias");
        jLabel6.setToolTipText("");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(370, 170, 680, 53);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(80, 170, 1410, 580);

        jPanel2.setBackground(new java.awt.Color(86, 90, 92));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/LogoUN.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1290, 0, 214, 110);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Servicio de pasantias");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(550, 30, 560, 53);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1660, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 1660, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingresar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_UsuarioActionPerformed

    private void Ingresar_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioMousePressed
        if (Ingresar_Usuario.getText().equals("Ingrese Usuario")){
            
            Ingresar_Usuario.setText("");
            Ingresar_Usuario.setForeground(Color.black);
  
        }
        
        if (String.valueOf(Ingresar_Pass.getPassword()).isEmpty()){
            
            Ingresar_Pass.setText("************");
            Ingresar_Pass.setForeground(Color.gray);   
        }
        
         
    }//GEN-LAST:event_Ingresar_UsuarioMousePressed

    private void Ingresar_UsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioMouseReleased
        
    }//GEN-LAST:event_Ingresar_UsuarioMouseReleased

    private void Ingresar_PassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_PassMousePressed

                
        if (Ingresar_Usuario.getText().isEmpty()){
            
            Ingresar_Usuario.setText("Ingrese Usuario");
            Ingresar_Usuario.setForeground(Color.gray);
  
        }
        
        if (String.valueOf(Ingresar_Pass.getPassword()).equals("************")){
            
            Ingresar_Pass.setText("");
            Ingresar_Pass.setForeground(Color.black);   
        }
    }//GEN-LAST:event_Ingresar_PassMousePressed

    private void Ingresar_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_PassActionPerformed

    private void asMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asMouseClicked
        
    }//GEN-LAST:event_asMouseClicked

    private void Boton_RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_RegistrarMouseClicked
        RegistroUser a = new RegistroUser();
        a.setVisible(true);  
        this.setVisible(false);
    }//GEN-LAST:event_Boton_RegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ass;
    private javax.swing.JLabel Boton_Ingresar;
    private javax.swing.JLabel Boton_Registrar;
    private javax.swing.JPasswordField Ingresar_Pass;
    private javax.swing.JTextField Ingresar_Usuario;
    private javax.swing.JPanel as;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
