/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.serviciopasantias.Vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import proyecto.serviciopasantias.Modelo.Estudiantes;
import proyecto.serviciopasantias.Vista.Login;

/**
 *
 * @author snsc2
 */
public class RegistroEstudiantes extends javax.swing.JPanel {

    /**
     * Creates new form RegistroEstudiantes
     */
    public RegistroEstudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SedeCombo = new javax.swing.JComboBox<>();
        IDCombo = new javax.swing.JComboBox<>();
        FacultadCombo = new javax.swing.JComboBox<>();
        LugarCombo = new javax.swing.JComboBox<>();
        CorreoEntry = new javax.swing.JTextField();
        ApellidoEntry = new javax.swing.JTextField();
        IDEntry = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TelefonoEntry = new javax.swing.JTextField();
        PassEntry1 = new javax.swing.JPasswordField();
        PassEntry2 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        ProgramaCombo = new javax.swing.JComboBox<>();
        NombreEntry = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        AvanceEntry = new javax.swing.JTextField();
        Boton_Registrar = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel4.setBackground(new java.awt.Color(236, 234, 234));
        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("No. ID:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(225, 120, 70, 25);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombres:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 20, 160, 25);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Apellidos:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 70, 150, 25);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tipo ID:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 120, 60, 25);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Facultad:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(500, 70, 70, 25);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Sede:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(500, 20, 50, 25);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Correo Institucional:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 270, 150, 25);

        SedeCombo.setBackground(new java.awt.Color(204, 204, 204));
        SedeCombo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        SedeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","Bogota", "Medellin", "Orinoquia", "Palmira","Manizales","Tumaco" }));
        SedeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SedeComboActionPerformed(evt);
            }
        });
        jPanel4.add(SedeCombo);
        SedeCombo.setBounds(550, 20, 370, 25);

        IDCombo.setBackground(new java.awt.Color(204, 204, 204));
        IDCombo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        IDCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "C.C.", "T.I.", "C.E."}));
        IDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDComboActionPerformed(evt);
            }
        });
        jPanel4.add(IDCombo);
        IDCombo.setBounds(95, 120, 120, 25);

        FacultadCombo.setBackground(new java.awt.Color(204, 204, 204));
        FacultadCombo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        FacultadCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " ,"Facultad de Ciencias Agrarias", "Facultad Artes", "Facultad de Ciencias", "Facultad de Enfermeria", "Facultad de Ciencias Humanas", "Facultad de Derecho", "Facultad de Ingenieria", "Facultad de Medicina", "Facultad de Odontologia", "Facultad de Medicina Veterinaria y Zootecnia", "Facultad de Ciencias Economicas", "Facultad de Arquitectura", "Facultad de Minas" }));
        FacultadCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultadComboActionPerformed(evt);
            }
        });
        jPanel4.add(FacultadCombo);
        FacultadCombo.setBounds(570, 70, 350, 25);

        LugarCombo.setBackground(new java.awt.Color(204, 204, 204));
        LugarCombo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LugarCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " ,"Bogotá", "Tunja", "Sogamoso"}));
        jPanel4.add(LugarCombo);
        LugarCombo.setBounds(180, 170, 255, 25);

        CorreoEntry.setBackground(new java.awt.Color(255, 255, 255));
        CorreoEntry.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        CorreoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(CorreoEntry);
        CorreoEntry.setBounds(170, 270, 265, 25);

        ApellidoEntry.setBackground(new java.awt.Color(255, 255, 255));
        ApellidoEntry.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ApellidoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(ApellidoEntry);
        ApellidoEntry.setBounds(95, 70, 340, 25);

        IDEntry.setBackground(new java.awt.Color(255, 255, 255));
        IDEntry.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        IDEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntryActionPerformed(evt);
            }
        });
        jPanel4.add(IDEntry);
        IDEntry.setBounds(280, 120, 155, 25);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Contraseña:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(500, 220, 90, 25);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Teléfono:");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(20, 220, 70, 25);

        TelefonoEntry.setBackground(new java.awt.Color(255, 255, 255));
        TelefonoEntry.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TelefonoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TelefonoEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoEntryActionPerformed(evt);
            }
        });
        jPanel4.add(TelefonoEntry);
        TelefonoEntry.setBounds(100, 220, 335, 25);

        PassEntry1.setBackground(new java.awt.Color(255, 255, 255));
        PassEntry1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        PassEntry1.setText("****************");
        PassEntry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PassEntry1.setPreferredSize(new java.awt.Dimension(69, 20));
        PassEntry1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PassEntry1MousePressed(evt);
            }
        });
        jPanel4.add(PassEntry1);
        PassEntry1.setBounds(600, 220, 315, 25);

        PassEntry2.setBackground(new java.awt.Color(255, 255, 255));
        PassEntry2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        PassEntry2.setText("****************");
        PassEntry2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PassEntry2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PassEntry2MousePressed(evt);
            }
        });
        PassEntry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassEntry2ActionPerformed(evt);
            }
        });
        jPanel4.add(PassEntry2);
        PassEntry2.setBounds(680, 270, 235, 25);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Programa curricular:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(500, 120, 150, 25);

        ProgramaCombo.setBackground(new java.awt.Color(204, 204, 204));
        ProgramaCombo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ProgramaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " ,"Administración de Empresas", "Antropología", "Arquictectura", "Artes Plasticas", "Administración de Sistemas Informaticos", "Biologia,Ciencia Política", "Ciencias de la Computación", "Cine y Televisión", "Contaduría Pública", "Construcción", "Derecho", "Diseño Grafico", "Diseño Industrial", "Economia", "Enfermeria", "Español y Filología Clasíca", "Estadistica", "Estudios Literarios", "Farmacia", "Filología e Idiomas:Alemán", "Filología e Idiomas:Francés", "Filología e Idiomas:Inglés", "Filología", "Física", "Fonoaudiología","Geografia","Geologia", "Gestión Cultural y Comunicativa", "Historia", "Ingeniería Agrícola", "Ingeniería Agronómica", "Ingeniería Civil", "Ingeniería de Sistemas y Computación", "Ingeniería Eléctrica", "Ingeniería Electrónica", "Ingeniería Industrial", "Ingeniería Mecánica", "Ingeniería Mecatrónica", "Ingeniería Química", "Ingeniería Fisica", "Ingeniería de Control", "Ingeniería de Minas y Metalurgia", "Ingeniería de Petroleos", "Ingeniería de Sistemas e Informatica", "Ingeniería Forestal","Ingeniería Geológica", "Matematicas", "Medicina", "Medicina Veterinaria", "Música", "Musica Instrumental", "Nutrición y Dietetica", "Odontologia", "Psicologia", "Quimica", "Sociologia", "Terepia Ocupacional", "Trabajo Social", "Zootecnía" }));
        ProgramaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramaComboActionPerformed(evt);
            }
        });
        jPanel4.add(ProgramaCombo);
        ProgramaCombo.setBounds(650, 120, 270, 25);

        NombreEntry.setBackground(new java.awt.Color(255, 255, 255));
        NombreEntry.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        NombreEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntryActionPerformed(evt);
            }
        });
        jPanel4.add(NombreEntry);
        NombreEntry.setBounds(95, 20, 340, 25);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Porcentaje avance:");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(500, 170, 140, 25);

        AvanceEntry.setBackground(new java.awt.Color(255, 255, 255));
        AvanceEntry.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        AvanceEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AvanceEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanceEntryActionPerformed(evt);
            }
        });
        jPanel4.add(AvanceEntry);
        AvanceEntry.setBounds(640, 170, 280, 25);

        Boton_Registrar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Registrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Registrar.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Registrar");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        Boton_Registrar.add(jLabel19);
        jLabel19.setBounds(0, 0, 280, 60);

        jPanel4.add(Boton_Registrar);
        Boton_Registrar.setBounds(330, 380, 280, 60);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Verifique su contraseña:");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(500, 270, 170, 25);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Lugar de Expedición:");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(20, 170, 170, 25);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jSeparator1);
        jSeparator1.setBounds(468, 0, 2, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SedeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SedeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SedeComboActionPerformed

    private void IDEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntryActionPerformed

    private void TelefonoEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoEntryActionPerformed

    private void IDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDComboActionPerformed

    private void NombreEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntryActionPerformed

    private void AvanceEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanceEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvanceEntryActionPerformed

    private void FacultadComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultadComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultadComboActionPerformed

    private void PassEntry1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassEntry1MousePressed
        if (String.valueOf(PassEntry1.getPassword()).equals("****************")){
            
            PassEntry1.setText("");
            PassEntry1.setForeground(Color.black);
  
        }
        
        if (String.valueOf(PassEntry2.getPassword()).isEmpty()){
            
            PassEntry2.setText("****************");
            PassEntry2.setForeground(Color.gray);   
        }
    }//GEN-LAST:event_PassEntry1MousePressed

    private void PassEntry2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassEntry2MousePressed
        if (String.valueOf(PassEntry2.getPassword()).equals("****************")){
            
            PassEntry2.setText("");
            PassEntry2.setForeground(Color.black);
  
        }
        
        if (String.valueOf(PassEntry1.getPassword()).isEmpty()){
            
            PassEntry1.setText("****************");
            PassEntry1.setForeground(Color.gray);   
        }
    }//GEN-LAST:event_PassEntry2MousePressed

    private void PassEntry2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassEntry2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassEntry2ActionPerformed

    private void ProgramaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramaComboActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if ("C.C.".equals(IDCombo.getSelectedItem().toString())){
            String resultado = Estudiantes.Register(IDEntry.getText(), "Cedula de ciudadania", LugarCombo.getSelectedItem().toString(), 
                    NombreEntry.getText(), ApellidoEntry.getText(), CorreoEntry.getText(), TelefonoEntry.getText(),
                    ProgramaCombo.getSelectedItem().toString(), AvanceEntry.getText());
            
            if ("Error".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Revise el registro.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
                
            else if ("Registro Exitoso".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Se ha hecho el registro de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                Login frame = new Login();
                frame.setVisible(true);  
                this.setVisible(false);
            }
                
            else if ("Ya Registrado".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Ya existe un usuario registrado con esa ID.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            
            /*else{
                JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }*/
        }
    }//GEN-LAST:event_jLabel19MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoEntry;
    private javax.swing.JTextField AvanceEntry;
    private javax.swing.JPanel Boton_Registrar;
    private javax.swing.JTextField CorreoEntry;
    private javax.swing.JComboBox<String> FacultadCombo;
    private javax.swing.JComboBox<String> IDCombo;
    private javax.swing.JTextField IDEntry;
    private javax.swing.JComboBox<String> LugarCombo;
    private javax.swing.JTextField NombreEntry;
    private javax.swing.JPasswordField PassEntry1;
    private javax.swing.JPasswordField PassEntry2;
    private javax.swing.JComboBox<String> ProgramaCombo;
    private javax.swing.JComboBox<String> SedeCombo;
    private javax.swing.JTextField TelefonoEntry;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
