/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.serviciopasantias.Vista.Menu_Estudiante;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import proyecto.serviciopasantias.Modelo.Estudiantes;
import proyecto.serviciopasantias.Modelo.LoginForAll;

/**
 *
 * @author Windows
 */
public class InformacionPersonalEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form InformacionPersonal
     */
    public InformacionPersonalEstudiante() {
        initComponents();
        Contraseña2.hide();
        NombreEntry.setText(Estudiantes.nombre);
        ApellidoEntry.setText(Estudiantes.apellido);
        IDEntry.setText(Estudiantes.tipo_id);
        IDEntry1.setText(Estudiantes.no_id);
        LugarEntry.setText(Estudiantes.lugar);
        TelefonoEntry.setText(Estudiantes.telefono);
        CorreoEntry.setText(Estudiantes.correo);
        SedeEntry.setText(Estudiantes.sede);
        FacultadEntry.setText(Estudiantes.facultad);
        ProgramaEntry.setText(Estudiantes.programa);
        AvanceEntry.setText(Estudiantes.avance);
        ContraseñaEntry.setText(LoginForAll.passwordu);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CorreoEntry = new javax.swing.JTextField();
        ApellidoEntry = new javax.swing.JTextField();
        IDEntry = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TelefonoEntry = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ProgramaEntry = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        AvanceEntry = new javax.swing.JTextField();
        Boton_Editar = new javax.swing.JPanel();
        LabelEditar = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NombreEntry = new javax.swing.JTextField();
        LugarEntry = new javax.swing.JTextField();
        FacultadEntry = new javax.swing.JTextField();
        SedeEntry = new javax.swing.JTextField();
        Boton_Guardar = new javax.swing.JPanel();
        LabelGuardar = new javax.swing.JLabel();
        IDEntry1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        Contraseña1 = new javax.swing.JLabel();
        Contraseña2 = new javax.swing.JLabel();
        ContraseñaEntry = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(1150, 420));

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("No. ID:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(325, 120, 70, 25);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Nombres:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 20, 160, 25);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Apellidos:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 70, 80, 25);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Tipo ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 120, 60, 25);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setText("Facultad:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(610, 120, 70, 25);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Sede:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(610, 70, 50, 25);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Correo Institucional:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 220, 150, 25);

        CorreoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CorreoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CorreoEntry.setEnabled(false);
        CorreoEntry.setNextFocusableComponent(ContraseñaEntry);
        jPanel1.add(CorreoEntry);
        CorreoEntry.setBounds(180, 220, 350, 25);

        ApellidoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ApellidoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ApellidoEntry.setEnabled(false);
        ApellidoEntry.setNextFocusableComponent(IDEntry);
        jPanel1.add(ApellidoEntry);
        ApellidoEntry.setBounds(130, 70, 400, 25);

        IDEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry.setEnabled(false);
        IDEntry.setNextFocusableComponent(IDEntry1);
        IDEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntryActionPerformed(evt);
            }
        });
        jPanel1.add(IDEntry);
        IDEntry.setBounds(130, 120, 190, 25);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setText("Teléfono:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(610, 20, 70, 25);

        TelefonoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TelefonoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TelefonoEntry.setEnabled(false);
        TelefonoEntry.setNextFocusableComponent(SedeEntry);
        TelefonoEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoEntryActionPerformed(evt);
            }
        });
        jPanel1.add(TelefonoEntry);
        TelefonoEntry.setBounds(710, 20, 400, 25);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setText("Programa curricular:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(610, 170, 150, 25);

        ProgramaEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ProgramaEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ProgramaEntry.setEnabled(false);
        ProgramaEntry.setNextFocusableComponent(AvanceEntry);
        ProgramaEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramaEntryActionPerformed(evt);
            }
        });
        jPanel1.add(ProgramaEntry);
        ProgramaEntry.setBounds(770, 170, 340, 25);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel22.setText("Porcentaje avance:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(610, 220, 140, 25);

        AvanceEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        AvanceEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AvanceEntry.setEnabled(false);
        AvanceEntry.setNextFocusableComponent(LabelGuardar);
        AvanceEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanceEntryActionPerformed(evt);
            }
        });
        jPanel1.add(AvanceEntry);
        AvanceEntry.setBounds(760, 220, 350, 25);

        Boton_Editar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Editar.setLayout(null);

        LabelEditar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEditar.setText("Editar");
        LabelEditar.setNextFocusableComponent(NombreEntry);
        LabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEditarMouseClicked(evt);
            }
        });
        LabelEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelEditarKeyPressed(evt);
            }
        });
        Boton_Editar.add(LabelEditar);
        LabelEditar.setBounds(0, 0, 280, 60);

        jPanel1.add(Boton_Editar);
        Boton_Editar.setBounds(595, 340, 280, 60);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("Lugar de Expedición:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 170, 170, 25);

        NombreEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry.setEnabled(false);
        NombreEntry.setFocusCycleRoot(true);
        NombreEntry.setNextFocusableComponent(ApellidoEntry);
        NombreEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntryActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry);
        NombreEntry.setBounds(130, 20, 400, 25);

        LugarEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LugarEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LugarEntry.setEnabled(false);
        LugarEntry.setNextFocusableComponent(CorreoEntry);
        LugarEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarEntryActionPerformed(evt);
            }
        });
        jPanel1.add(LugarEntry);
        LugarEntry.setBounds(190, 170, 340, 25);

        FacultadEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        FacultadEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FacultadEntry.setEnabled(false);
        FacultadEntry.setNextFocusableComponent(ProgramaEntry);
        FacultadEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultadEntryActionPerformed(evt);
            }
        });
        jPanel1.add(FacultadEntry);
        FacultadEntry.setBounds(710, 120, 400, 25);

        SedeEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        SedeEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SedeEntry.setEnabled(false);
        SedeEntry.setNextFocusableComponent(FacultadEntry);
        SedeEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SedeEntryActionPerformed(evt);
            }
        });
        jPanel1.add(SedeEntry);
        SedeEntry.setBounds(710, 70, 400, 25);

        Boton_Guardar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Guardar.setLayout(null);

        LabelGuardar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGuardar.setText("Guardar");
        LabelGuardar.setEnabled(false);
        LabelGuardar.setNextFocusableComponent(LabelEditar);
        LabelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelGuardarMouseClicked(evt);
            }
        });
        LabelGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelGuardarKeyPressed(evt);
            }
        });
        Boton_Guardar.add(LabelGuardar);
        LabelGuardar.setBounds(0, 0, 280, 60);

        jPanel1.add(Boton_Guardar);
        Boton_Guardar.setBounds(275, 340, 280, 60);

        IDEntry1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDEntry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry1.setEnabled(false);
        IDEntry1.setNextFocusableComponent(LugarEntry);
        IDEntry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntry1ActionPerformed(evt);
            }
        });
        jPanel1.add(IDEntry1);
        IDEntry1.setBounds(380, 120, 150, 25);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(573, 0, 2, 300);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("Contraseña:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 270, 150, 25);

        Contraseña1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/PasswordUn1.png"))); // NOI18N
        Contraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Contraseña1MouseClicked(evt);
            }
        });
        jPanel1.add(Contraseña1);
        Contraseña1.setBounds(500, 273, 20, 20);

        Contraseña2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/eye1.png"))); // NOI18N
        Contraseña2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Contraseña2MouseClicked(evt);
            }
        });
        jPanel1.add(Contraseña2);
        Contraseña2.setBounds(500, 273, 20, 20);

        ContraseñaEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ContraseñaEntry.setText("jPasswordField1");
        ContraseñaEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContraseñaEntry.setEnabled(false);
        ContraseñaEntry.setNextFocusableComponent(TelefonoEntry);
        jPanel1.add(ContraseñaEntry);
        ContraseñaEntry.setBounds(130, 270, 400, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IDEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntryActionPerformed

    private void TelefonoEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoEntryActionPerformed

    private void ProgramaEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramaEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramaEntryActionPerformed

    private void AvanceEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanceEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvanceEntryActionPerformed

    private void LabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEditarMouseClicked
        String pass = JOptionPane.showInputDialog("Ingrese su contraseña para hacer cambios");
        if (pass.equals(LoginForAll.passwordu)){
            LabelEditar.setEnabled(false);
            LabelGuardar.setEnabled(true);
            ContraseñaEntry.setEnabled(true);
            TelefonoEntry.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LabelEditarMouseClicked

    private void LabelEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelEditarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String pass = JOptionPane.showInputDialog("Ingrese su contraseña para hacer cambios");
            if (pass.equals(LoginForAll.passwordu)){
                LabelEditar.setEnabled(false);
                LabelGuardar.setEnabled(true);
                ContraseñaEntry.setEnabled(true);
                TelefonoEntry.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            }           
        }
    }//GEN-LAST:event_LabelEditarKeyPressed

    private void NombreEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntryActionPerformed

    private void LugarEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarEntryActionPerformed

    private void FacultadEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultadEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultadEntryActionPerformed

    private void SedeEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SedeEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SedeEntryActionPerformed

    private void LabelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelGuardarMouseClicked
        String resultado = Estudiantes.CambiarDatos(ContraseñaEntry.getText(), LoginForAll.usuario, TelefonoEntry.getText());
        if (resultado.equals("Datos Actualizados")){
            JOptionPane.showMessageDialog(this, "Los datos han sido actualizados con éxito", "Cambio Exitoso", JOptionPane.INFORMATION_MESSAGE);
            LabelEditar.setEnabled(true);
            LabelGuardar.setEnabled(false);
            ContraseñaEntry.setEnabled(false);
            TelefonoEntry.setEnabled(false);
        }
        else if (resultado.equals("Error")){
            JOptionPane.showMessageDialog(this, "Ha habido un error en el cambio de credenciales", "Error", JOptionPane.ERROR_MESSAGE);   
        }
        else{             
            JOptionPane.showMessageDialog(this, resultado , "Ingreso Fallido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LabelGuardarMouseClicked

    private void LabelGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelGuardarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String resultado = Estudiantes.CambiarDatos(ContraseñaEntry.getText(), LoginForAll.usuario, TelefonoEntry.getText());
            if (resultado.equals("Datos Actualizados")){
               JOptionPane.showMessageDialog(this, "Los datos han sido actualizados con éxito", "Cambio Exitoso", JOptionPane.INFORMATION_MESSAGE);
               LabelEditar.setEnabled(true);
               LabelGuardar.setEnabled(false);
               ContraseñaEntry.setEnabled(false);
               TelefonoEntry.setEnabled(false);
            }
            else if (resultado.equals("Error")){
                JOptionPane.showMessageDialog(this, "Ha habido un error en el cambio de credenciales", "Error", JOptionPane.ERROR_MESSAGE);   
            }
            else{             
                JOptionPane.showMessageDialog(this, resultado , "Ingreso Fallido", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_LabelGuardarKeyPressed

    private void IDEntry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntry1ActionPerformed

    private void Contraseña2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contraseña2MouseClicked
        if (ContraseñaEntry.isEnabled() == true){
            ContraseñaEntry.setEchoChar('*');
            Contraseña1.show();
            Contraseña1.setEnabled(true);
            Contraseña2.hide();
            Contraseña2.setEnabled(false);
        }
    }//GEN-LAST:event_Contraseña2MouseClicked

    private void Contraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contraseña1MouseClicked
        if (ContraseñaEntry.isEnabled() == true){
            ContraseñaEntry.setEchoChar((char)0);
            Contraseña2.show();
            Contraseña2.setEnabled(true);
            Contraseña1.hide();
            Contraseña1.setEnabled(false);
        }
    }//GEN-LAST:event_Contraseña1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoEntry;
    private javax.swing.JTextField AvanceEntry;
    private javax.swing.JPanel Boton_Editar;
    private javax.swing.JPanel Boton_Guardar;
    private javax.swing.JLabel Contraseña1;
    private javax.swing.JLabel Contraseña2;
    private javax.swing.JPasswordField ContraseñaEntry;
    private javax.swing.JTextField CorreoEntry;
    private javax.swing.JTextField FacultadEntry;
    private javax.swing.JTextField IDEntry;
    private javax.swing.JTextField IDEntry1;
    private javax.swing.JLabel LabelEditar;
    private javax.swing.JLabel LabelGuardar;
    private javax.swing.JTextField LugarEntry;
    private javax.swing.JTextField NombreEntry;
    private javax.swing.JTextField ProgramaEntry;
    private javax.swing.JTextField SedeEntry;
    private javax.swing.JTextField TelefonoEntry;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
