/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.serviciopasantias.Vista.Menu_Estudiante;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.serviciopasantias.Modelo.Conexion;

/**
 *
 * @author Windows
 */
public final class PasantiasDisponiblesEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form InformacionPersonal
     */
    public PasantiasDisponiblesEstudiante() {
        initComponents();
        mostrar();
    }
    
    
    
    public void mostrar()
    {
        String []  nombresColumnas = {"Empresa","Descripción","Estado"};
        String [] registros = new String[3];
        
        DefaultTableModel modelo = new DefaultTableModel(null,nombresColumnas){
            
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            };
            
        };
        
        
        String sql = "SELECT * FROM actividad";
        
        Connection cn = null;
        
        PreparedStatement pst = null;
        
        ResultSet rs = null;
        
        try
        {
            cn = Conexion.conectar();
            
            pst = cn.prepareStatement(sql);                        
            
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                registros[0] = rs.getString("TITULO");
                
                registros[1] = rs.getString("DESCRIPCION");
                
                registros[2] = rs.getString("RESPONSABLE");
                
                modelo.addRow(registros);
                
            }
            
            visor.setModel(modelo);
            
           
        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,"Error al conectar");
            
        }
        finally
        {
            try
            {
                if (rs != null) rs.close();
                
                if (pst != null) pst.close();
                
                if (cn != null) cn.close();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }

    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        Ass = new javax.swing.JPanel();
        Boton_Ingresar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1150, 420));

        jPanel1.setLayout(null);

        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(visor);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 1100, 290);

        Ass.setBackground(new java.awt.Color(148, 180, 59));
        Ass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Ass.setLayout(null);

        Boton_Ingresar.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        Boton_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_Ingresar.setText("Ingresar");
        Boton_Ingresar.setToolTipText("");
        Boton_Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_IngresarMouseClicked(evt);
            }
        });
        Boton_Ingresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Boton_IngresarKeyPressed(evt);
            }
        });
        Ass.add(Boton_Ingresar);
        Boton_Ingresar.setBounds(0, 0, 250, 60);

        jPanel1.add(Ass);
        Ass.setBounds(450, 340, 250, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_IngresarMouseClicked

        
    }//GEN-LAST:event_Boton_IngresarMouseClicked

    private void Boton_IngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Boton_IngresarKeyPressed

    }//GEN-LAST:event_Boton_IngresarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ass;
    private javax.swing.JLabel Boton_Ingresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
