/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.serviciopasantias.Vista.Menu_Estudiante;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import proyecto.serviciopasantias.Modelo.Actividad;
import proyecto.serviciopasantias.Modelo.ComboBoxes;
import proyecto.serviciopasantias.Modelo.Pasantia;
import proyecto.serviciopasantias.Modelo.LoginForAll;
import proyecto.serviciopasantias.Vista.Menu_Estudiante.PasantiasDisponiblesEstudiante;

/**
 *
 * @author snsc2
 */
public class RegistrarPasantía extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPasantía
     */
    public RegistrarPasantía() {
        initComponents();
        this.setLocationRelativeTo(null);
        jtfTitulo.setText(Actividad.titulo);
        jtaDescripcion.setText(Actividad.descripcion);
        jtfTipologia.setText(Actividad.tipologia);
        jtfFecha_inicio.setText(Actividad.fecha_inicio);
        jtfFecha_fin.setText(Actividad.fecha_fin);
        jtfubicacion.setText(Actividad.ubicacion);
        ComboBoxes cb = new ComboBoxes();
        DocentesCombo.setModel(cb.getValuesDocentes());
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfFecha_inicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfFecha_fin = new javax.swing.JTextField();
        jtfTipologia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        Boton_Guardar1 = new javax.swing.JPanel();
        LabelAgregar = new javax.swing.JLabel();
        A9 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfubicacion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfOGeneral = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfOEspecifico1 = new javax.swing.JTextField();
        A3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfOEspecifico2 = new javax.swing.JTextField();
        A4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtfOEspecifico3 = new javax.swing.JTextField();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaIntro = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaJustificacion = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaAporte = new javax.swing.JTextArea();
        A8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        DocentesCombo = new javax.swing.JComboBox<>();
        A1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 730));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(86, 90, 92));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 110));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/LogoUN.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(970, 0, 230, 90);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Aplicar a la pasantía");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 1200, 90);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1200, 90);

        jPanel1.setForeground(new java.awt.Color(148, 180, 59));
        jPanel1.setLayout(null);

        jPanel3.setPreferredSize(new java.awt.Dimension(1150, 470));
        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        jPanel5.setMinimumSize(new java.awt.Dimension(1150, 470));

        jPanel6.setPreferredSize(new java.awt.Dimension(1150, 470));
        jPanel6.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel25.setText("Tipologia:");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(20, 180, 200, 25);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Descripción:");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(20, 70, 120, 25);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Fecha fin:");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(20, 280, 120, 25);

        jtfFecha_inicio.setBackground(new java.awt.Color(255, 255, 255));
        jtfFecha_inicio.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfFecha_inicio.setForeground(new java.awt.Color(0, 0, 0));
        jtfFecha_inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfFecha_inicio.setEnabled(false);
        jtfFecha_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFecha_inicioActionPerformed(evt);
            }
        });
        jPanel6.add(jtfFecha_inicio);
        jtfFecha_inicio.setBounds(130, 230, 420, 25);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Titulo:");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(20, 20, 110, 25);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Fecha inicio:");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(20, 230, 130, 25);

        jtfFecha_fin.setBackground(new java.awt.Color(255, 255, 255));
        jtfFecha_fin.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfFecha_fin.setForeground(new java.awt.Color(0, 0, 0));
        jtfFecha_fin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfFecha_fin.setEnabled(false);
        jtfFecha_fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFecha_finActionPerformed(evt);
            }
        });
        jPanel6.add(jtfFecha_fin);
        jtfFecha_fin.setBounds(130, 280, 420, 25);

        jtfTipologia.setBackground(new java.awt.Color(255, 255, 255));
        jtfTipologia.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfTipologia.setForeground(new java.awt.Color(0, 0, 0));
        jtfTipologia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfTipologia.setEnabled(false);
        jPanel6.add(jtfTipologia);
        jtfTipologia.setBounds(130, 180, 420, 25);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtaDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jtaDescripcion.setColumns(20);
        jtaDescripcion.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtaDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jtaDescripcion.setLineWrap(true);
        jtaDescripcion.setRows(5);
        jtaDescripcion.setEnabled(false);
        jtaDescripcion.setPreferredSize(new java.awt.Dimension(400, 105));
        jtaDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtaDescripcion);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(130, 70, 420, 80);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jSeparator1);
        jSeparator1.setBounds(600, 0, 2, 480);

        Boton_Guardar1.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Guardar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Guardar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Guardar1.setLayout(null);

        LabelAgregar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAgregar.setText("Agregar");
        LabelAgregar.setName(""); // NOI18N
        LabelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAgregarMouseClicked(evt);
            }
        });
        LabelAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelAgregarKeyPressed(evt);
            }
        });
        Boton_Guardar1.add(LabelAgregar);
        LabelAgregar.setBounds(0, 0, 280, 60);

        jPanel6.add(Boton_Guardar1);
        Boton_Guardar1.setBounds(470, 510, 280, 60);

        A9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A9.setForeground(new java.awt.Color(255, 0, 51));
        A9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A9.setText("Las casillas marcadas con un * son obligatorias.");
        jPanel6.add(A9);
        A9.setBounds(0, 570, 1200, 21);

        A2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A2.setForeground(new java.awt.Color(255, 0, 51));
        A2.setText("*");
        jPanel6.add(A2);
        A2.setBounds(555, 420, 10, 15);

        jtfTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jtfTitulo.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jtfTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfTitulo.setEnabled(false);
        jPanel6.add(jtfTitulo);
        jtfTitulo.setBounds(130, 20, 420, 25);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("Ubicación:");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(20, 330, 120, 25);

        jtfubicacion.setBackground(new java.awt.Color(255, 255, 255));
        jtfubicacion.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfubicacion.setForeground(new java.awt.Color(0, 0, 0));
        jtfubicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfubicacion.setEnabled(false);
        jtfubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfubicacionActionPerformed(evt);
            }
        });
        jPanel6.add(jtfubicacion);
        jtfubicacion.setBounds(130, 330, 420, 25);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setText("Objetivo General:");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(20, 380, 140, 25);

        jtfOGeneral.setBackground(new java.awt.Color(255, 255, 255));
        jtfOGeneral.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfOGeneral.setForeground(new java.awt.Color(0, 0, 0));
        jtfOGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfOGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOGeneralActionPerformed(evt);
            }
        });
        jPanel6.add(jtfOGeneral);
        jtfOGeneral.setBounds(170, 380, 380, 25);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("Objetivo Específico 1:");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(640, 20, 157, 25);

        jtfOEspecifico1.setBackground(new java.awt.Color(255, 255, 255));
        jtfOEspecifico1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfOEspecifico1.setForeground(new java.awt.Color(0, 0, 0));
        jtfOEspecifico1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfOEspecifico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOEspecifico1ActionPerformed(evt);
            }
        });
        jPanel6.add(jtfOEspecifico1);
        jtfOEspecifico1.setBounds(810, 20, 350, 25);

        A3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A3.setForeground(new java.awt.Color(255, 0, 51));
        A3.setText("*");
        jPanel6.add(A3);
        A3.setBounds(1165, 10, 10, 15);

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel18.setText("Objetivo Específico 2:");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(640, 70, 170, 25);

        jtfOEspecifico2.setBackground(new java.awt.Color(255, 255, 255));
        jtfOEspecifico2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfOEspecifico2.setForeground(new java.awt.Color(0, 0, 0));
        jtfOEspecifico2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfOEspecifico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOEspecifico2ActionPerformed(evt);
            }
        });
        jPanel6.add(jtfOEspecifico2);
        jtfOEspecifico2.setBounds(810, 70, 350, 25);

        A4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A4.setForeground(new java.awt.Color(255, 0, 51));
        A4.setText("*");
        jPanel6.add(A4);
        A4.setBounds(1165, 60, 10, 15);

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel19.setText("Objetivo Específico 3:");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(640, 120, 160, 25);

        jtfOEspecifico3.setBackground(new java.awt.Color(255, 255, 255));
        jtfOEspecifico3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtfOEspecifico3.setForeground(new java.awt.Color(0, 0, 0));
        jtfOEspecifico3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfOEspecifico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOEspecifico3ActionPerformed(evt);
            }
        });
        jPanel6.add(jtfOEspecifico3);
        jtfOEspecifico3.setBounds(810, 120, 350, 25);

        A5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A5.setForeground(new java.awt.Color(255, 0, 51));
        A5.setText("*");
        jPanel6.add(A5);
        A5.setBounds(1165, 110, 10, 15);

        A6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A6.setForeground(new java.awt.Color(255, 0, 51));
        A6.setText("*");
        jPanel6.add(A6);
        A6.setBounds(1165, 160, 10, 15);

        A7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A7.setForeground(new java.awt.Color(255, 0, 51));
        A7.setText("*");
        jPanel6.add(A7);
        A7.setBounds(1165, 270, 10, 15);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setText("Introducción:");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(640, 170, 120, 25);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtaIntro.setBackground(new java.awt.Color(255, 255, 255));
        jtaIntro.setColumns(20);
        jtaIntro.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtaIntro.setForeground(new java.awt.Color(0, 0, 0));
        jtaIntro.setLineWrap(true);
        jtaIntro.setRows(5);
        jtaIntro.setPreferredSize(new java.awt.Dimension(400, 105));
        jtaIntro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaIntroKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtaIntro);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(740, 170, 420, 80);

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel21.setText("Justificación:");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(640, 280, 120, 25);

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtaJustificacion.setBackground(new java.awt.Color(255, 255, 255));
        jtaJustificacion.setColumns(20);
        jtaJustificacion.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtaJustificacion.setForeground(new java.awt.Color(0, 0, 0));
        jtaJustificacion.setLineWrap(true);
        jtaJustificacion.setRows(5);
        jtaJustificacion.setPreferredSize(new java.awt.Dimension(400, 105));
        jtaJustificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaJustificacionKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jtaJustificacion);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(740, 280, 420, 80);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel22.setText("Aplicación Aporte:");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(640, 390, 140, 25);

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtaAporte.setBackground(new java.awt.Color(255, 255, 255));
        jtaAporte.setColumns(20);
        jtaAporte.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jtaAporte.setForeground(new java.awt.Color(0, 0, 0));
        jtaAporte.setLineWrap(true);
        jtaAporte.setRows(5);
        jtaAporte.setPreferredSize(new java.awt.Dimension(400, 105));
        jtaAporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaAporteKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(jtaAporte);

        jPanel6.add(jScrollPane4);
        jScrollPane4.setBounds(780, 390, 380, 80);

        A8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A8.setForeground(new java.awt.Color(255, 0, 51));
        A8.setText("*");
        jPanel6.add(A8);
        A8.setBounds(1165, 380, 10, 15);

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel23.setText("Código Docente Encargado:");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(20, 430, 210, 25);

        DocentesCombo.setBackground(new java.awt.Color(255, 255, 255));
        DocentesCombo.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        DocentesCombo.setForeground(new java.awt.Color(0, 0, 0));
        DocentesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " , "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Distrito Capital", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Risaralda", "San Andrés y Providencia", "Santander", "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada"}));
        DocentesCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DocentesComboItemStateChanged(evt);
            }
        });
        jPanel6.add(DocentesCombo);
        DocentesCombo.setBounds(230, 430, 320, 25);

        A1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        A1.setForeground(new java.awt.Color(255, 0, 51));
        A1.setText("*");
        jPanel6.add(A1);
        A1.setBounds(555, 370, 10, 15);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Quedan 100 carácteres.");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(1020, 470, 140, 16);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setText("Quedan 100 carácteres.");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(1020, 250, 140, 16);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setText("Quedan 100 carácteres.");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(1020, 360, 140, 16);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 1200, 640);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 1200, 640);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1200, 640);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 90, 1200, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfFecha_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFecha_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFecha_inicioActionPerformed

    private void jtfFecha_finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFecha_finActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFecha_finActionPerformed

    private void jtaDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaDescripcionKeyTyped

    }//GEN-LAST:event_jtaDescripcionKeyTyped

    private void LabelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAgregarMouseClicked
        registrarPasantia();
    }//GEN-LAST:event_LabelAgregarMouseClicked

    private void LabelAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelAgregarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            /*registrarPasantia();*/
        }
    }//GEN-LAST:event_LabelAgregarKeyPressed

    public void registrarPasantia(){
        A1.setVisible(false);
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        A6.setVisible(false);
        A7.setVisible(false);
        A8.setVisible(false);
        A9.setVisible(false);
        int contador = 0;
        if ("".equals(jtfOGeneral.getText()))
        {
            contador += 1;
            A1.setVisible(true);
        }
        if (" ".equals(DocentesCombo.getSelectedItem().toString()))
        {
            contador += 1;
            A2.setVisible(true);
        }
        if ("".equals(jtfOEspecifico1.getText()))
        {
            contador += 1;
            A3.setVisible(true);
        }
        if ("".equals(jtaIntro.getText()))
        {
            contador += 1;
            A6.setVisible(true);
        }
        if ("".equals(jtaJustificacion.getText()))
        {
            contador += 1;
            A7.setVisible(true);
        }
        if ("".equals(jtaAporte.getText()))
        {
            contador += 1;
            A8.setVisible(true);
        }
        String objetivo2;
        String objetivo3;
        if ("".equals(jtfOEspecifico2.getText()))
        {
            objetivo2 = null;
        }
        else{
            objetivo2 = jtfOEspecifico2.getText();
        }
        if ("".equals(jtfOEspecifico3.getText()))
        {
            objetivo3 = null;
        }
        else{
            objetivo3 = jtfOEspecifico3.getText();
        }
        if (contador > 0){
            A9.setVisible(true);
        }
        else{
            String resultado = Pasantia.RegistrarPasantia(LoginForAll.es_id, jtfTitulo.getText(), jtfOGeneral.getText(), jtaIntro.getText(), jtaJustificacion.getText(),
                    jtaAporte.getText(), jtfFecha_inicio.getText(), jtfFecha_fin.getText(), jtfOEspecifico1.getText(), objetivo2, objetivo3, PasantiasDisponiblesEstudiante.empresa,
                    DocentesCombo.getSelectedItem().toString());
            
            if ("Error".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Revise el registro.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
                
            else if ("Aplicacion Exitosa".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Se ha aplicado de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
               
            else{
                JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void jtfubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfubicacionActionPerformed

    private void jtfOGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOGeneralActionPerformed

    private void jtfOEspecifico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOEspecifico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOEspecifico1ActionPerformed

    private void jtfOEspecifico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOEspecifico2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOEspecifico2ActionPerformed

    private void jtfOEspecifico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOEspecifico3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOEspecifico3ActionPerformed

    private void jtaIntroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaIntroKeyTyped
        String s = jtaIntro.getText();
        int l = s.length();
        int resultado = 100 - l;
        try{
            if (l >= 100){evt.consume();}
        }
        catch(Exception w){}
        jLabel6.setText("Quedan "+ resultado + " carácteres");
    }//GEN-LAST:event_jtaIntroKeyTyped

    private void jtaJustificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaJustificacionKeyTyped
        String s = jtaJustificacion.getText();
        int l = s.length();
        int resultado = 100 - l;
        try{
            if (l >= 100){evt.consume();}
        }
        catch(Exception w){}
        jLabel7.setText("Quedan "+ resultado + " carácteres");
    }//GEN-LAST:event_jtaJustificacionKeyTyped

    private void jtaAporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaAporteKeyTyped
        String s = jtaAporte.getText();
        int l = s.length();
        int resultado = 100 - l;
        try{
            if (l >= 100){evt.consume();}
        }
        catch(Exception w){}
        jLabel4.setText("Quedan "+ resultado + " carácteres");
    }//GEN-LAST:event_jtaAporteKeyTyped

    private void DocentesComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DocentesComboItemStateChanged
        
    }//GEN-LAST:event_DocentesComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPasantía.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPasantía.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPasantía.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPasantía.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPasantía().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel A9;
    private javax.swing.JPanel Boton_Guardar1;
    private javax.swing.JComboBox<String> DocentesCombo;
    private javax.swing.JLabel LabelAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jtaAporte;
    private javax.swing.JTextArea jtaDescripcion;
    private javax.swing.JTextArea jtaIntro;
    private javax.swing.JTextArea jtaJustificacion;
    private javax.swing.JTextField jtfFecha_fin;
    private javax.swing.JTextField jtfFecha_inicio;
    private javax.swing.JTextField jtfOEspecifico1;
    private javax.swing.JTextField jtfOEspecifico2;
    private javax.swing.JTextField jtfOEspecifico3;
    private javax.swing.JTextField jtfOGeneral;
    private javax.swing.JTextField jtfTipologia;
    private javax.swing.JTextField jtfTitulo;
    private javax.swing.JTextField jtfubicacion;
    // End of variables declaration//GEN-END:variables
}
