/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.serviciopasantias.Vista.Menu_Comite;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import proyecto.serviciopasantias.Modelo.Empresas;
import proyecto.serviciopasantias.Modelo.Validar;

/**
 *
 * @author snsc2
 */
public class ValidarEmpresas extends javax.swing.JFrame {

    /**
     * Creates new form ValidarEmpresas
     */
    public ValidarEmpresas() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(ValidarEmpresas.DISPOSE_ON_CLOSE);
        NombreEmpEntry.setText(Empresas.nombreemp);
        NITEntry.setText(Empresas.nit);
        CorreoEmpEntry.setText(Empresas.correoemp);
        TelefonoEmpEntry.setText(Empresas.telefonoemp);
        CiudadEmpEntry.setText(Empresas.ciudad);
        NombreRepEntry.setText(Empresas.nombrerep);
        ApellidoRepEntry.setText(Empresas.apellidorep);
        IDEntry.setText(Empresas.tipo_id);
        IDEntry1.setText(Empresas.no_id);
        LugarEntry.setText(Empresas.lugar);
        CorreoRepEntry.setText(Empresas.correorep);
        TelefonoRepEntry.setText(Empresas.telefonorep);
        CargoRepEntry.setText(Empresas.cargorep);
        AreaRepEntry.setText(Empresas.arearep);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Editar = new javax.swing.JPanel();
        LabelValidar = new javax.swing.JLabel();
        Boton_Guardar = new javax.swing.JPanel();
        LabelNoValidar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TelefonoEmpEntry = new javax.swing.JTextField();
        NITEntry = new javax.swing.JTextField();
        IDEntry = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CiudadEmpEntry = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CorreoRepEntry = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        CargoRepEntry = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        NombreEmpEntry = new javax.swing.JTextField();
        CorreoEmpEntry = new javax.swing.JTextField();
        LugarEntry = new javax.swing.JTextField();
        NombreRepEntry = new javax.swing.JTextField();
        IDEntry1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        ApellidoRepEntry = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TelefonoRepEntry = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        AreaRepEntry = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1150, 600));
        getContentPane().setLayout(null);

        jPanel1.setForeground(new java.awt.Color(148, 180, 59));
        jPanel1.setLayout(null);

        Boton_Editar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Editar.setLayout(null);

        LabelValidar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelValidar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValidar.setText("Validar");
        LabelValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelValidarMouseClicked(evt);
            }
        });
        LabelValidar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelValidarKeyPressed(evt);
            }
        });
        Boton_Editar.add(LabelValidar);
        LabelValidar.setBounds(0, 0, 280, 60);

        jPanel1.add(Boton_Editar);
        Boton_Editar.setBounds(600, 400, 280, 60);

        Boton_Guardar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Guardar.setLayout(null);

        LabelNoValidar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelNoValidar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNoValidar.setText("No Validar");
        LabelNoValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelNoValidarMouseClicked(evt);
            }
        });
        LabelNoValidar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelNoValidarKeyPressed(evt);
            }
        });
        Boton_Guardar.add(LabelNoValidar);
        LabelNoValidar.setBounds(0, 0, 280, 60);

        jPanel1.add(Boton_Guardar);
        Boton_Guardar.setBounds(280, 400, 280, 60);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("No. ID:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(905, 40, 70, 25);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Nombre de la Empresa:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 40, 180, 25);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("NIT:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 90, 100, 25);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Tipo ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 40, 60, 25);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setText("Lugar de Expedición:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(610, 90, 160, 25);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Nombre del Representante:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 290, 210, 25);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Teléfono de la Empresa:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 190, 180, 25);

        TelefonoEmpEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TelefonoEmpEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TelefonoEmpEntry.setEnabled(false);
        jPanel1.add(TelefonoEmpEntry);
        TelefonoEmpEntry.setBounds(210, 190, 320, 25);

        NITEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NITEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NITEntry.setEnabled(false);
        jPanel1.add(NITEntry);
        NITEntry.setBounds(130, 90, 400, 25);

        IDEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry.setEnabled(false);
        IDEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntryActionPerformed(evt);
            }
        });
        jPanel1.add(IDEntry);
        IDEntry.setBounds(710, 40, 190, 25);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setText("Ciudad de la Empresa:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(30, 240, 170, 25);

        CiudadEmpEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CiudadEmpEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CiudadEmpEntry.setEnabled(false);
        CiudadEmpEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadEmpEntryActionPerformed(evt);
            }
        });
        jPanel1.add(CiudadEmpEntry);
        CiudadEmpEntry.setBounds(210, 240, 320, 25);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setText("Correo del Representante:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(610, 140, 200, 25);

        CorreoRepEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CorreoRepEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CorreoRepEntry.setEnabled(false);
        CorreoRepEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoRepEntryActionPerformed(evt);
            }
        });
        jPanel1.add(CorreoRepEntry);
        CorreoRepEntry.setBounds(810, 140, 300, 25);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel22.setText("Cargo del Representante:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(610, 240, 200, 25);

        CargoRepEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CargoRepEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CargoRepEntry.setEnabled(false);
        CargoRepEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoRepEntryActionPerformed(evt);
            }
        });
        jPanel1.add(CargoRepEntry);
        CargoRepEntry.setBounds(800, 240, 305, 25);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("Correo de la Empresa:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 140, 170, 25);

        NombreEmpEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEmpEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEmpEntry.setEnabled(false);
        NombreEmpEntry.setFocusCycleRoot(true);
        NombreEmpEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEmpEntryActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEmpEntry);
        NombreEmpEntry.setBounds(210, 40, 320, 25);

        CorreoEmpEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CorreoEmpEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CorreoEmpEntry.setEnabled(false);
        CorreoEmpEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoEmpEntryActionPerformed(evt);
            }
        });
        jPanel1.add(CorreoEmpEntry);
        CorreoEmpEntry.setBounds(200, 140, 330, 25);

        LugarEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LugarEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LugarEntry.setEnabled(false);
        LugarEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarEntryActionPerformed(evt);
            }
        });
        jPanel1.add(LugarEntry);
        LugarEntry.setBounds(770, 90, 340, 25);

        NombreRepEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreRepEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreRepEntry.setEnabled(false);
        NombreRepEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreRepEntryActionPerformed(evt);
            }
        });
        jPanel1.add(NombreRepEntry);
        NombreRepEntry.setBounds(240, 290, 290, 25);

        IDEntry1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDEntry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry1.setEnabled(false);
        IDEntry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntry1ActionPerformed(evt);
            }
        });
        jPanel1.add(IDEntry1);
        IDEntry1.setBounds(960, 40, 150, 25);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(570, 0, 2, 370);

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel24.setText("Apellidos del Representante:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(30, 340, 210, 25);

        ApellidoRepEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ApellidoRepEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ApellidoRepEntry.setEnabled(false);
        ApellidoRepEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoRepEntryActionPerformed(evt);
            }
        });
        jPanel1.add(ApellidoRepEntry);
        ApellidoRepEntry.setBounds(240, 340, 285, 25);

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel26.setText("Teléfono del Representante:");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(610, 190, 210, 25);

        TelefonoRepEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TelefonoRepEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TelefonoRepEntry.setEnabled(false);
        TelefonoRepEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoRepEntryActionPerformed(evt);
            }
        });
        jPanel1.add(TelefonoRepEntry);
        TelefonoRepEntry.setBounds(820, 190, 290, 25);

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel27.setText("Área del Representante:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(610, 290, 200, 25);

        AreaRepEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        AreaRepEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AreaRepEntry.setEnabled(false);
        AreaRepEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaRepEntryActionPerformed(evt);
            }
        });
        jPanel1.add(AreaRepEntry);
        AreaRepEntry.setBounds(790, 290, 315, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 90, 1150, 510);

        jPanel2.setBackground(new java.awt.Color(86, 90, 92));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 110));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/LogoUN.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(920, 0, 230, 90);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Validar Empresas y Empresarios");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 1150, 90);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1150, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelValidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelValidarMouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea validar a este usuario?", "Validar", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            String s1 = CorreoRepEntry.getText();
            String[] user =s1.split("@");
            String id = IDEntry1.getText();
            String resultado = Validar.ValidarEmpresas(user[0], id, s1);
            if ("Error".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Revise el registro.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else if ("Registro Exitoso".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Se ha hecho el registro de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
            else if ("Ya Registrado".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Ya existe un usuario registrado con esa ID.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        }
    }//GEN-LAST:event_LabelValidarMouseClicked

    private void LabelValidarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelValidarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea validar a este usuario?", "Validar", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                String s1 = CorreoRepEntry.getText();
                String[] user =s1.split("@");
                String id = IDEntry1.getText();
                String resultado = Validar.ValidarEmpresas(user[0], id, s1);
                if ("Error".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Revise el registro.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                else if ("Registro Exitoso".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Se ha hecho el registro de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                }
                else if ("Ya Registrado".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Ya existe un usuario registrado con esa ID.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_LabelValidarKeyPressed

    private void LabelNoValidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNoValidarMouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea eliminar a este usuario?", " No Validar", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            String nit = NITEntry.getText();
            String id = IDEntry1.getText();
            String resultado = Validar.NoValidarEmpresas(nit, id);
            if ("Error".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Revise la operación.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else if ("Proceso Exitoso".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Se ha eliminado el usuario de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
            else if ("No Existe".equals(resultado)){
                JOptionPane.showMessageDialog(this, "El usuario no existe", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        }
    }//GEN-LAST:event_LabelNoValidarMouseClicked

    private void LabelNoValidarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelNoValidarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea eliminar a este usuario?", " No Validar", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                String nit = NITEntry.getText();
                String id = IDEntry1.getText();
                String resultado = Validar.NoValidarEmpresas(nit, id);
                if ("Error".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Revise la operación.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                else if ("Proceso Exitoso".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Se ha eliminado el usuario de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                }
                else if ("No Existe".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "El usuario no existe", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_LabelNoValidarKeyPressed

    private void IDEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntryActionPerformed

    private void CiudadEmpEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadEmpEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiudadEmpEntryActionPerformed

    private void CorreoRepEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoRepEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoRepEntryActionPerformed

    private void CargoRepEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoRepEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargoRepEntryActionPerformed

    private void NombreEmpEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEmpEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEmpEntryActionPerformed

    private void CorreoEmpEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoEmpEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoEmpEntryActionPerformed

    private void LugarEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarEntryActionPerformed

    private void NombreRepEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreRepEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreRepEntryActionPerformed

    private void IDEntry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntry1ActionPerformed

    private void ApellidoRepEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoRepEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoRepEntryActionPerformed

    private void TelefonoRepEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoRepEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoRepEntryActionPerformed

    private void AreaRepEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaRepEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaRepEntryActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoRepEntry;
    private javax.swing.JTextField AreaRepEntry;
    private javax.swing.JPanel Boton_Editar;
    private javax.swing.JPanel Boton_Guardar;
    private javax.swing.JTextField CargoRepEntry;
    private javax.swing.JTextField CiudadEmpEntry;
    private javax.swing.JTextField CorreoEmpEntry;
    private javax.swing.JTextField CorreoRepEntry;
    private javax.swing.JTextField IDEntry;
    private javax.swing.JTextField IDEntry1;
    private javax.swing.JLabel LabelNoValidar;
    private javax.swing.JLabel LabelValidar;
    private javax.swing.JTextField LugarEntry;
    private javax.swing.JTextField NITEntry;
    private javax.swing.JTextField NombreEmpEntry;
    private javax.swing.JTextField NombreRepEntry;
    private javax.swing.JTextField TelefonoEmpEntry;
    private javax.swing.JTextField TelefonoRepEntry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
