/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.serviciopasantias.Vista.Menu_Comite;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import proyecto.serviciopasantias.Modelo.Docentes;
import proyecto.serviciopasantias.Modelo.Validar;

/**
 *
 * @author snsc2
 */
public class ValidarDocentes extends javax.swing.JFrame {

    /**
     * Creates new form ValidarDocentes
     */
    public ValidarDocentes() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(ValidarEmpresas.DISPOSE_ON_CLOSE);
        NombreEntry.setText(Docentes.nombre);
        ApellidoEntry.setText(Docentes.apellido);
        IDEntry.setText(Docentes.tipo_id);
        IDEntry1.setText(Docentes.no_id);
        LugarEntry.setText(Docentes.lugar);
        TelefonoEntry.setText(Docentes.telefono);
        TelefonoEntry1.setText(Docentes.extension);
        CorreoEntry.setText(Docentes.correo);
        DepartamentoEntry.setText(Docentes.departamento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Editar = new javax.swing.JPanel();
        LabelValidar = new javax.swing.JLabel();
        Boton_Guardar = new javax.swing.JPanel();
        LabelNoValidar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NombreEntry = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ApellidoEntry = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        IDEntry = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IDEntry1 = new javax.swing.JTextField();
        LugarEntry = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        DepartamentoEntry = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TelefonoEntry1 = new javax.swing.JTextField();
        TelefonoEntry = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CorreoEntry = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 560));
        getContentPane().setLayout(null);

        jPanel1.setForeground(new java.awt.Color(148, 180, 59));
        jPanel1.setLayout(null);

        Boton_Editar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Editar.setLayout(null);

        LabelValidar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelValidar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValidar.setText("Validar");
        LabelValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelValidarMouseClicked(evt);
            }
        });
        LabelValidar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelValidarKeyPressed(evt);
            }
        });
        Boton_Editar.add(LabelValidar);
        LabelValidar.setBounds(0, 0, 280, 60);

        jPanel1.add(Boton_Editar);
        Boton_Editar.setBounds(600, 260, 280, 60);

        Boton_Guardar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Boton_Guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Boton_Guardar.setLayout(null);

        LabelNoValidar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelNoValidar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNoValidar.setText("No Validar");
        LabelNoValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelNoValidarMouseClicked(evt);
            }
        });
        LabelNoValidar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelNoValidarKeyPressed(evt);
            }
        });
        Boton_Guardar.add(LabelNoValidar);
        LabelNoValidar.setBounds(0, 0, 280, 60);

        jPanel1.add(Boton_Guardar);
        Boton_Guardar.setBounds(280, 260, 280, 60);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Nombres:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 20, 160, 25);

        NombreEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        NombreEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEntry.setEnabled(false);
        NombreEntry.setFocusCycleRoot(true);
        NombreEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntryActionPerformed(evt);
            }
        });
        jPanel1.add(NombreEntry);
        NombreEntry.setBounds(130, 20, 400, 25);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Apellidos:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 70, 80, 25);

        ApellidoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ApellidoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ApellidoEntry.setEnabled(false);
        jPanel1.add(ApellidoEntry);
        ApellidoEntry.setBounds(130, 70, 400, 25);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Tipo ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 120, 60, 25);

        IDEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry.setEnabled(false);
        IDEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntryActionPerformed(evt);
            }
        });
        jPanel1.add(IDEntry);
        IDEntry.setBounds(130, 120, 190, 25);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("No. ID:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(325, 120, 70, 25);

        IDEntry1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        IDEntry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDEntry1.setEnabled(false);
        IDEntry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEntry1ActionPerformed(evt);
            }
        });
        jPanel1.add(IDEntry1);
        IDEntry1.setBounds(380, 120, 150, 25);

        LugarEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LugarEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LugarEntry.setEnabled(false);
        LugarEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarEntryActionPerformed(evt);
            }
        });
        jPanel1.add(LugarEntry);
        LugarEntry.setBounds(190, 170, 340, 25);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("Lugar de Expedición:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 170, 170, 25);

        DepartamentoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        DepartamentoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DepartamentoEntry.setEnabled(false);
        DepartamentoEntry.setFocusCycleRoot(true);
        DepartamentoEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoEntryActionPerformed(evt);
            }
        });
        jPanel1.add(DepartamentoEntry);
        DepartamentoEntry.setBounds(730, 170, 380, 25);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Departamento:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(610, 170, 110, 25);

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel24.setText("Extensión:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(610, 120, 70, 25);

        TelefonoEntry1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TelefonoEntry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TelefonoEntry1.setEnabled(false);
        TelefonoEntry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoEntry1ActionPerformed(evt);
            }
        });
        jPanel1.add(TelefonoEntry1);
        TelefonoEntry1.setBounds(710, 120, 400, 25);

        TelefonoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TelefonoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TelefonoEntry.setEnabled(false);
        TelefonoEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoEntryActionPerformed(evt);
            }
        });
        jPanel1.add(TelefonoEntry);
        TelefonoEntry.setBounds(710, 70, 400, 25);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setText("Teléfono:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(610, 70, 70, 25);

        CorreoEntry.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CorreoEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CorreoEntry.setEnabled(false);
        jPanel1.add(CorreoEntry);
        CorreoEntry.setBounds(760, 20, 350, 25);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Correo Institucional:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(610, 20, 150, 25);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(573, 0, 2, 200);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 90, 1150, 380);

        jPanel2.setBackground(new java.awt.Color(86, 90, 92));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 110));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/serviciopasantias/Vista/Images/LogoUN.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(920, 0, 230, 90);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Validar Docentes");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 1150, 90);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1150, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelValidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelValidarMouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea validar a este usuario?", "Validar", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            String s1 = CorreoEntry.getText();
            String[] user =s1.split("@");
            String id = IDEntry1.getText();
            String resultado = Validar.ValidarDocentee(user[0], id, s1);
            if ("Error".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Revise el registro.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else if ("Registro Exitoso".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Se ha hecho el registro de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
            else if ("Ya Registrado".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Ya existe un usuario registrado con esa ID.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        }
    }//GEN-LAST:event_LabelValidarMouseClicked

    private void LabelValidarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelValidarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea validar a este usuario?", "Validar", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                String s1 = CorreoEntry.getText();
                String[] user =s1.split("@");
                String id = IDEntry1.getText();
                String resultado = Validar.ValidarDocentee(user[0], id, s1);
                if ("Error".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Revise el registro.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                else if ("Registro Exitoso".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Se ha hecho el registro de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                }
                else if ("Ya Registrado".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Ya existe un usuario registrado con esa ID.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_LabelValidarKeyPressed

    private void LabelNoValidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNoValidarMouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea eliminar a este usuario?", " No Validar", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            String id = IDEntry1.getText();
            String resultado = Validar.NoValidarDocente(id);
            if ("Error".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Revise la operación.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else if ("Proceso Exitoso".equals(resultado)){
                JOptionPane.showMessageDialog(this, "Se ha eliminado el usuario de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
            else if ("No Existe".equals(resultado)){
                JOptionPane.showMessageDialog(this, "El usuario no existe", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        }
    }//GEN-LAST:event_LabelNoValidarMouseClicked

    private void LabelNoValidarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelNoValidarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int reply = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea eliminar a este usuario?", " No Validar", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                String id = IDEntry1.getText();
                String resultado = Validar.NoValidarDocente(id);
                if ("Error".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Revise la operación.", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                else if ("Proceso Exitoso".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "Se ha eliminado el usuario de forma exitosa.", "Registro Exitoso.", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                }
                else if ("No Existe".equals(resultado)){
                    JOptionPane.showMessageDialog(this, "El usuario no existe", "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, resultado, "Registro Fallido", JOptionPane.ERROR_MESSAGE);
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_LabelNoValidarKeyPressed

    private void NombreEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntryActionPerformed

    private void IDEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntryActionPerformed

    private void IDEntry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEntry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEntry1ActionPerformed

    private void LugarEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarEntryActionPerformed

    private void DepartamentoEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartamentoEntryActionPerformed

    private void TelefonoEntry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoEntry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoEntry1ActionPerformed

    private void TelefonoEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoEntryActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoEntry;
    private javax.swing.JPanel Boton_Editar;
    private javax.swing.JPanel Boton_Guardar;
    private javax.swing.JTextField CorreoEntry;
    private javax.swing.JTextField DepartamentoEntry;
    private javax.swing.JTextField IDEntry;
    private javax.swing.JTextField IDEntry1;
    private javax.swing.JLabel LabelNoValidar;
    private javax.swing.JLabel LabelValidar;
    private javax.swing.JTextField LugarEntry;
    private javax.swing.JTextField NombreEntry;
    private javax.swing.JTextField TelefonoEntry;
    private javax.swing.JTextField TelefonoEntry1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
