/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistaControlador;

import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author snsc2
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Logim
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Ingresar_Usuario = new javax.swing.JTextField();
        Boton_Iniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Ingresar_Pass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(148, 180, 59));
        jPanel1.setForeground(new java.awt.Color(148, 180, 59));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(86, 90, 92));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿No está registrado? Cree su cuenta.");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 380, 910, 30);
        jPanel3.add(jLabel7);
        jLabel7.setBounds(330, 200, 0, 0);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 56, 980, 0);

        Ingresar_Usuario.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        Ingresar_Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Ingresar_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ingresar_Usuario.setText("Ingrese Usuario");
        Ingresar_Usuario.setToolTipText("Usuario");
        Ingresar_Usuario.setBorder(null);
        Ingresar_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ingresar_Usuario.setName(""); // NOI18N
        Ingresar_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ingresar_UsuarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Ingresar_UsuarioMouseReleased(evt);
            }
        });
        Ingresar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_UsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(Ingresar_Usuario);
        Ingresar_Usuario.setBounds(320, 193, 300, 50);

        Boton_Iniciar.setBackground(new java.awt.Color(148, 180, 59));
        Boton_Iniciar.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Boton_Iniciar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Iniciar.setText("Iniciar Sesión");
        Boton_Iniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_IniciarActionPerformed(evt);
            }
        });
        jPanel3.add(Boton_Iniciar);
        Boton_Iniciar.setBounds(390, 330, 171, 39);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingrese su usuario y contraseña");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 990, 53);
        jPanel3.add(jLabel8);
        jLabel8.setBounds(330, 270, 0, 0);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(350, 370, 250, 50);

        Ingresar_Pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ingresar_Pass.setText("************");
        Ingresar_Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ingresar_PassMousePressed(evt);
            }
        });
        jPanel3.add(Ingresar_Pass);
        Ingresar_Pass.setBounds(320, 260, 300, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(190, 210, 970, 450);

        jPanel2.setBackground(new java.awt.Color(86, 90, 92));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 0, 0, 110);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Servicio de pasantias");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(390, 30, 560, 53);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 40, 0, 0);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 40, 0, 0);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1660, 0);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void Ingresar_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioMousePressed
        if (Ingresar_Usuario.getText().equals("Ingrese Usuario")){
            Ingresar_Usuario.setText("");
            Ingresar_Usuario.setForeground(Color.black);
        }
        if (String.valueOf(Ingresar_Pass.getPassword()).isEmpty()){
            Ingresar_Pass.setText("************");
            Ingresar_Pass.setForeground(Color.gray);
        }

    }//GEN-LAST:event_Ingresar_UsuarioMousePressed

    private void Ingresar_UsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioMouseReleased

    }//GEN-LAST:event_Ingresar_UsuarioMouseReleased

    private void Ingresar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_UsuarioActionPerformed

    private void Boton_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_IniciarActionPerformed
        MainCardLayout frame = new MainCardLayout();
        if ("Ingrese Usuario".equals(Ingresar_Usuario.getText()) && "************".equals(Ingresar_Pass.getText())){
            JOptionPane.showMessageDialog(frame, "Las casillas de usuario y contraseña se encuentran vacías.", "Campos Vacíos", JOptionPane.ERROR_MESSAGE);   
        }
        else if ("Ingrese Usuario".equals(Ingresar_Usuario.getText()) && "".equals(Ingresar_Pass.getText())){
            JOptionPane.showMessageDialog(frame, "Las casillas de usuario y contraseña se encuentran vacías.", "Campos Vacíos", JOptionPane.ERROR_MESSAGE);   
        }
        else if ("".equals(Ingresar_Usuario.getText()) && "************".equals(Ingresar_Pass.getText())){
            JOptionPane.showMessageDialog(frame, "Las casillas de usuario y contraseña se encuentran vacías.", "Campos Vacíos", JOptionPane.ERROR_MESSAGE);   
        }
        else{
            String resultado = Modelo.LoginForAll.Login(Ingresar_Usuario.getText(), Ingresar_Pass.getText());
            if ("Error".equals(resultado)){
                JOptionPane.showMessageDialog(frame, "Revise sus credenciales.", "Ingreso Fallido", JOptionPane.ERROR_MESSAGE);
            }
            else if ("Estudiante".equals(resultado)){
                frame.showMenuEst();
                JOptionPane.showMessageDialog(frame, "Bienvenido a la plataforma, estudiante.", "Ingreso Correcto", JOptionPane.INFORMATION_MESSAGE);
            }
            else if ("Docente".equals(resultado)){
                JOptionPane.showMessageDialog(frame, "Bienvenido a la plataforma, docente.", "Ingreso Fallido", JOptionPane.OK_OPTION);
                frame.showMenuDoc();
            }
            else if ("Empresa".equals(resultado)){
                frame.showMenuEmp();
                JOptionPane.showMessageDialog(frame, "Bienvenido a la plataforma, empresario.", "Ingreso Fallido", JOptionPane.OK_OPTION);
            }
            else{
                JOptionPane.showMessageDialog(frame, resultado, "Ingreso Fallido", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Boton_IniciarActionPerformed

    private void Ingresar_PassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingresar_PassMousePressed

        if (Ingresar_Usuario.getText().isEmpty()){
            Ingresar_Usuario.setText("Ingrese Usuario");
            Ingresar_Usuario.setForeground(Color.gray);
        }
        if (String.valueOf(Ingresar_Pass.getPassword()).equals("************")){
            Ingresar_Pass.setText("");
            Ingresar_Pass.setForeground(Color.black);
        }
    }//GEN-LAST:event_Ingresar_PassMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Iniciar;
    private javax.swing.JPasswordField Ingresar_Pass;
    private javax.swing.JTextField Ingresar_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
